name: CI/CD

on:
  push:
    branches: [development]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          for service in auth gyms memberships sports tournaments; do
            docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/${service}-service:${{ github.sha }} ./backend/modules/$service
            docker push ${{ secrets.DOCKERHUB_USERNAME }}/${service}-service:${{ github.sha }}
          done

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Import existing resources from Terraform state
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
        run: |
          cd terraform
          terraform init
          terraform import aws_key_pair.deployer powerfitconnect-key || true
          terraform import aws_security_group.service_sg sg-0f846caccd93d6fd1 || true

      - name: Terraform Apply
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
        run: |
          cd terraform
          terraform apply -auto-approve

      - name: Deploy microservices to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOSTS }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            for service in auth gyms memberships sports tournaments; do
              docker pull ${{ secrets.DOCKERHUB_USERNAME }}/${service}-service:${{ github.sha }}
              docker stop ${service}-service || true
              docker rm ${service}-service || true
              docker run -d --name ${service}-service -p 5${RANDOM:0:3}:5000 ${{ secrets.DOCKERHUB_USERNAME }}/${service}-service:${{ github.sha }}
            done
